/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerRecord {
  'id' : string,
  'source' : string,
  'name' : string,
  'timestamp' : Timestamp,
}
export type LoginResult = { 'ok' : null } |
  { 'err' : string };
export type RegisterResult = { 'ok' : null } |
  { 'err' : string };
export type SaveCustomerResult = { 'ok' : CustomerRecord } |
  { 'err' : string };
export interface SummaryRecord {
  'id' : bigint,
  'customerName' : string,
  'source' : string,
  'filename' : string,
  'summary' : string,
  'timestamp' : Timestamp,
  'customName' : string,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UploadResult = { 'ok' : string } |
  { 'err' : string };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'analyzeFile' : ActorMethod<
    [string, Uint8Array, string, string, string],
    UploadResult
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<CustomerRecord>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomers' : ActorMethod<[string], Array<CustomerRecord>>,
  'getSummaries' : ActorMethod<[], Array<SummaryRecord>>,
  'getSummariesByCustomer' : ActorMethod<[string], Array<SummaryRecord>>,
  'getSummariesBySource' : ActorMethod<[string], Array<SummaryRecord>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], LoginResult>,
  'register' : ActorMethod<[string, string], RegisterResult>,
  'saveCustomer' : ActorMethod<[string, string], SaveCustomerResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'usernameExists' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];