/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UploadResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const CustomerRecord = IDL.Record({
  'id' : IDL.Text,
  'source' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : Timestamp,
});
export const SummaryRecord = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'source' : IDL.Text,
  'filename' : IDL.Text,
  'summary' : IDL.Text,
  'timestamp' : Timestamp,
  'customName' : IDL.Text,
});
export const LoginResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const RegisterResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
});
export const SaveCustomerResult = IDL.Variant({
  'ok' : CustomerRecord,
  'err' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'analyzeFile' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text, IDL.Text, IDL.Text],
      [UploadResult],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerRecord)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomers' : IDL.Func([IDL.Text], [IDL.Vec(CustomerRecord)], ['query']),
  'getSummaries' : IDL.Func([], [IDL.Vec(SummaryRecord)], ['query']),
  'getSummariesByCustomer' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SummaryRecord)],
      ['query'],
    ),
  'getSummariesBySource' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SummaryRecord)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'register' : IDL.Func([IDL.Text, IDL.Text], [RegisterResult], []),
  'saveCustomer' : IDL.Func([IDL.Text, IDL.Text], [SaveCustomerResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'usernameExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UploadResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const CustomerRecord = IDL.Record({
    'id' : IDL.Text,
    'source' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const SummaryRecord = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'source' : IDL.Text,
    'filename' : IDL.Text,
    'summary' : IDL.Text,
    'timestamp' : Timestamp,
    'customName' : IDL.Text,
  });
  const LoginResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const RegisterResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const SaveCustomerResult = IDL.Variant({
    'ok' : CustomerRecord,
    'err' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'analyzeFile' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text, IDL.Text, IDL.Text],
        [UploadResult],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerRecord)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomers' : IDL.Func([IDL.Text], [IDL.Vec(CustomerRecord)], ['query']),
    'getSummaries' : IDL.Func([], [IDL.Vec(SummaryRecord)], ['query']),
    'getSummariesByCustomer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SummaryRecord)],
        ['query'],
      ),
    'getSummariesBySource' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SummaryRecord)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'register' : IDL.Func([IDL.Text, IDL.Text], [RegisterResult], []),
    'saveCustomer' : IDL.Func([IDL.Text, IDL.Text], [SaveCustomerResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'usernameExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };